solution 1-9
mate-academy/react_people-table pull request #10
Opened 2019-07-13 07:44 UTC by OlgaLyubicheva

2019-07-15 14:31 UTC, vkryvytskyi requested changes
по клику не выделяется строка с пользователем, доделывай оставшиеся задания

2019-07-15 14:31 UTC, volodymyrkryvytskyy commented on src/App.js
> +    const usersValue = event.target.value;
const { value } = event.target

2019-07-15 14:31 UTC, volodymyrkryvytskyy commented on src/App.js
> +    console.log('render', ' filtredPeople:', filtredPeople);
Это можно удалить

2019-07-15 14:31 UTC, volodymyrkryvytskyy commented on src/PeopleTable.js
> +  const cursorPointer = { cursor: 'pointer' };
Это можно в css прописать для всех кликабельных <th>

2019-07-15 14:31 UTC, volodymyrkryvytskyy commented on src/PeopleTable.js
> +const isSorted = (people, sortWay, fieldOfSort) => {
функцию нужно назвать глаголом, отражающим то что она делает -  sortPeople к примеру

2019-07-15 14:31 UTC, volodymyrkryvytskyy commented on src/PeopleTable.js
> +  sortPeople = isSorted(people, sortStatus, fieldOfSort);
sortedPeople - отсортированные люди

2019-07-17 10:21 UTC, vkryvytskyi requested changes

2019-07-17 10:21 UTC, volodymyrkryvytskyy commented on src/components/newPerson/NewPerson.js
> +          Add new person
После ввода данных новый человек в таблице появляется только после сортировки/фильтрации. Сделай так чтобы он появлялся автоматически

2019-07-18 09:38 UTC, vpolets requested changes

2019-07-18 09:38 UTC, vpolets commented on src/App.js
> +    fetch('./api/people.json')
винось fetch окремий файл, компонент не має мати можливість напряму працювати з api

2019-07-18 09:38 UTC, vpolets commented on src/App.js
> +          const byFather = getArrFromName(currentPerson.father, value);
getArrFromName назва функції каже що я отримаю масив з імені, а повертає насправді true or false

2019-07-18 09:38 UTC, vpolets commented on src/components/newPerson/NewPerson.js
> +    const { people, updateAppState } = this.props;
А навіщо формі знати про існування people? Її функція це зібрати об'єкт в якого будуть потрібні поля, можливо провести валідацію і віддати його, його не має цікавити, що там зверху, тим більше міняти state батьківського компоненту звідси це не зовсім очевидне рішення. Винеси setState в батьківський елемент і створи там метод addPerson = (person) => { set state: arr: [...prevArr, person] } схематично щось таке

2019-07-18 09:38 UTC, vpolets commented on src/components/newPerson/NewPerson.js
> +    possibleParents = this.props.people.filter(person => (
А ти people тут використовуєш, зрозумів, але state батьківського елементу міняй в батьківському елементі.

2019-07-18 09:38 UTC, vpolets commented on src/components/peopleTable/PeopleTable.js
> +let fieldOfSort = 'id';
чому 6-7 не в state?

2019-07-18 09:38 UTC, vpolets commented on src/components/peopleTable/PeopleTable.js
> +  const getFildOfSort = (event) => {
field

2019-07-18 09:38 UTC, vpolets commented on src/components/peopleTable/PeopleTable.js
> +    const currentRow = event.target.parentNode;
Ні. З dom ми в react напряму не працюємо. Міняй в state selectedRowId і якщо RowId === selectedRowId тоді накидуй потрібний клас

2019-07-18 09:38 UTC, vpolets commented on src/components/person/Person.js
> +  const namesOfchildren = children.map(kid => kid.name);
chield більш звичніше

2019-07-22 08:31 UTC, vpolets requested changes

2019-07-22 08:31 UTC, vpolets commented on src/App.js
> +    fetch('./api/people.json')
Чому не фіксиш?

2019-07-22 08:31 UTC, vpolets commented on src/App.js
> +          const byFather = getArrFromName(currentPerson.father, value);
Чому не фіксиш?

2019-07-22 08:31 UTC, vpolets commented on src/components/person/Person.js
> +  const namesOfchildren = children.map(child => child.name);
Ці обрахунки треба було робити, ще при підготовці даних, зараз при перерендері ти кожен раз робитимеш ті ж самі обчислення, а для чого, якщо можна було зробити всі обчислення ще при заваньаженні, так як ми робили в todo list of posts де ми одразу записували юзера і коментарі, щоб потім їх не шукати

2019-07-22 08:31 UTC, vpolets commented on src/components/peopleTable/PeopleTable.js
> +  let funcSort;
11-22 рядок це вже окремий метод getSortCallback старайся робити функції простішими. Якщо назва каже, що функція сортує, не треба їй давати додатковий функціонал у вигляді пошуку методу для сортування

2019-07-23 07:42 UTC, vkryvytskyi approved these changes

2019-07-23 07:42 UTC, volodymyrkryvytskyy commented on src/components/peopleTable/PeopleTable.js
> +    return (a, b) => 0;
return 0?

2025-06-05 14:21 UTC, closed without merging